const employeeData = [
    {
    id: 1,
    name: 'Ali Hassan',
    email: 'employee1@example.com',
    password: '123',
    tasks: [
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Create website",
    taskDescription: "Create a business website",
    taskDate: "11-02-2024",
    category: "Development",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Update website",
    taskDescription: "Update a business website",
    taskDate: "11-04-2024",
    category: "Development",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Create mobile app",
    taskDescription: "Create a business mobile app",
    taskDate: "11-06-2024",
    category: "Development",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Test mobile app",
    taskDescription: "Test a business mobile app",
    taskDate: "11-08-2024",
    category: "Testing",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Deploy mobile app",
    taskDescription: "Deploy a business mobile app",
    taskDate: "11-10-2024",
    category: "Deployment",
    },
    ],
    },
    {
    id: 2,
    name: 'Ahmed Ali',
    email: 'employee2@example.com',
    password: '123',
    tasks: [
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Create marketing campaign",
    taskDescription: "Create a marketing campaign for a business",
    taskDate: "11-02-2024",
    category: "Marketing",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Launch marketing campaign",
    taskDescription: "Launch a marketing campaign for a business",
    taskDate: "11-04-2024",
    category: "Marketing",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Analyze marketing campaign",
    taskDescription: "Analyze a marketing campaign for a business",
    taskDate: "11-06-2024",
    category: "Marketing",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Optimize marketing campaign",
    taskDescription: "Optimize a marketing campaign for a business",
    taskDate: "11-08-2024",
    category: "Marketing",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Report marketing campaign",
    taskDescription: "Report a marketing campaign for a business",
    taskDate: "11-10-2024",
    category: "Marketing",
    },
    ],
    },
    {
    id: 3,
    name: 'Faisal Khan',
    email: 'employee3@example.com',
    password: '123',
    tasks: [
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Conduct team meeting",
    taskDescription: "Conduct a team meeting to discuss project progress",
    taskDate: "11-02-2024",
    category: "Management",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Review project progress",
    taskDescription: "Review project progress and provide feedback",
    taskDate: "11-04-2024",
    category: "Management",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Assign new tasks",
    taskDescription: "Assign new tasks to team members",
    taskDate: "11-06-2024",
    category: "Management",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Monitor team performance",
    taskDescription: "Monitor team performance and provide feedback",
    taskDate: "11-08-2024",
    category: "Management",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Evaluate project success",
    taskDescription: "Evaluate project success and identify areas for improvement",
    taskDate: "11-10-2024",
    category: "Management",
    },
    ],
    },
    {
    id: 4,
    name: 'Imran Ahmed',
    email: 'employee4@example.com',
    password: '123',
    tasks: [
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Design new product",
    taskDescription: "Design a new product for the company",
    taskDate: "11-02-2024",
    category: "Design",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Test new product",
    taskDescription: "Test the new product for quality and functionality",
    taskDate: "11-04-2024",
    category: "Testing",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Launch new product",
    taskDescription: "Launch the new product in the market",
    taskDate: "11-06-2024",
    category: "Marketing",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Monitor product sales",
    taskDescription: "Monitor the sales of the new product",
    taskDate: "11-08-2024",
    category: "Sales",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Analyze product feedback",
    taskDescription: "Analyze the feedback from customers about the new product",
    taskDate: "11-10-2024",
    category: "Analysis",
    },
    ],
    },
    {
    id: 5,
    name: 'Javed Iqbal',
    email: 'employee5@example.com',
    password: '123',
    tasks: [
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Develop new feature",
    taskDescription: "Develop a new feature for the company's software",
    taskDate: "11-02-2024",
    category: "Development",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Test new feature",
    taskDescription: "Test the new feature for quality and functionality",
    taskDate: "11-04-2024",
    category: "Testing",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Deploy new feature",
    taskDescription: "Deploy the new feature to the production environment",
    taskDate: "11-06-2024",
    category: "Deployment",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Monitor feature performance",
    taskDescription: "Monitor the performance of the new feature",
    taskDate: "11-08-2024",
    category: "Monitoring",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Analyze feature feedback",
    taskDescription: "Analyze the feedback from customers about the new feature",
    taskDate: "11-10-2024",
    category: "Analysis",
    },
    ],
    },
    {
    id: 6,
    name: 'Kamran Khan',
    email: 'employee6@example.com',
    password: '123',
    tasks: [
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Create social media campaign",
    taskDescription: "Create a social media campaign for the company",
    taskDate: "11-02-2024",
    category: "Marketing",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Launch social media campaign",
    taskDescription: "Launch the social media campaign",
    taskDate: "11-04-2024",
    category: "Marketing",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Monitor social media engagement",
    taskDescription: "Monitor the engagement on social media",
    taskDate: "11-06-2024",
    category: "Monitoring",
    },
    {
    active: false,
    new: true,
    completed: false,
    failed: false,
    taskTitle: "Analyze social media metrics",
    taskDescription: "Analyze the metrics from the social media campaign",
    taskDate: "11-08-2024",
    category: "Analysis",
    },
    {
    active: true,
    new: false,
    completed: false,
    failed: false,
    taskTitle: "Optimize social media campaign",
    taskDescription: "Optimize the social media campaign based on the metrics",
    taskDate: "11-10-2024",
    category: "Optimization",
    },
    ],
    },
    {
    id: 7,
    name: 'Mohammed Ali',
    email: 'employee7@example.com',
    password: '123',
    tasks: [
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Create sales report",
        taskDescription: "Create a sales report for the company",
        taskDate: "11-02-2024",
        category: "Sales",
        },
        {
        active: false,
        new: true,
        completed: false,
        failed: false,
        taskTitle: "Analyze sales data",
        taskDescription: "Analyze the sales data for the company",
        taskDate: "11-04-2024",
        category: "Analysis",
        },
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Identify sales trends",
        taskDescription: "Identify the sales trends for the company",
        taskDate: "11-06-2024",
        category: "Analysis",
        },
        {
        active: false,
        new: true,
        completed: false,
        failed: false,
        taskTitle: "Develop sales strategy",
        taskDescription: "Develop a sales strategy for the company",
        taskDate: "11-08-2024",
        category: "Strategy",
        },
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Implement sales strategy",
        taskDescription: "Implement the sales strategy for the company",
        taskDate: "11-10-2024",
        category: "Implementation",
        },
        ],
        },
        {
        id: 8,
        name: 'Noman Ahmed',
        email: 'employee8@example.com',
        password: '123',
        tasks: [
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Conduct market research",
        taskDescription: "Conduct market research for the company",
        taskDate: "11-02-2024",
        category: "Research",
        },
        {
        active: false,
        new: true,
        completed: false,
        failed: false,
        taskTitle: "Analyze market trends",
        taskDescription: "Analyze the market trends for the company",
        taskDate: "11-04-2024",
        category: "Analysis",
        },
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Develop marketing strategy",
        taskDescription: "Develop a marketing strategy for the company",
        taskDate: "11-06-2024",
        category: "Strategy",
        },
        {
        active: false,
        new: true,
        completed: false,
        failed: false,
        taskTitle: "Implement marketing strategy",
        taskDescription: "Implement the marketing strategy for the company",
        taskDate: "11-08-2024",
        category: "Implementation",
        },
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Monitor marketing performance",
        taskDescription: "Monitor the marketing performance for the company",
        taskDate: "11-10-2024",
        category: "Monitoring",
        },
        ],
        },
        {
        id: 9,
        name: 'Omer Khan',
        email: 'employee9@example.com',
        password: '123',
        tasks: [
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Develop new product",
        taskDescription: "Develop a new product for the company",
        taskDate: "11-02-2024",
        category: "Development",
        },
        {
        active: false,
        new: true,
        completed: false,
        failed: false,
        taskTitle: "Test new product",
        taskDescription: "Test the new product for quality and functionality",
        taskDate: "11-04-2024",
        category: "Testing",
        },
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Launch new product",
        taskDescription: "Launch the new product in the market",
        taskDate: "11-06-2024",
        category: "Marketing",
        },
        {
        active: false,
        new: true,
        completed: false,
        failed: false,
        taskTitle: "Monitor product sales",
        taskDescription: "Monitor the sales of the new product",
        taskDate: "11-08-2024",
        category: "Sales",
        },
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Analyze product feedback",
        taskDescription: "Analyze the feedback from customers about the new product",
        taskDate: "11-10-2024",
        category: "Analysis",
        },
        ],
        },
        {
        id: 10,
        name: 'Rashid Ali',
        email: 'employee10@example.com',
        password: '123',
        tasks: [
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Create training program",
        taskDescription: "Create a training program for new employees",
        taskDate: "11-02-2024",
        category: "Training",
        },
        {
        active: false,
        new: true,
        completed: false,
        failed: false,
        taskTitle: "Conduct training sessions",
        taskDescription: "Conduct training sessions for new employees",
        taskDate: "11-04-2024",
        category: "Training",
        },
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Evaluate training effectiveness",
        taskDescription: "Evaluate the effectiveness of the training program",
        taskDate: "11-06-2024",
        category: "Evaluation",
        },
        {
        active: false,
        new: true,
        completed: false,
        failed: false,
        taskTitle: "Improve training program",
        taskDescription: "Improve the training program based on feedback",
        taskDate: "11-08-2024",
        category: "Improvement",
        },
        {
        active: true,
        new: false,
        completed: false,
        failed: false,
        taskTitle: "Develop training manual",
        taskDescription: "Develop a training manual for new employees",
        taskDate: "11-10-2024",
        category: "Documentation",
        },
        ],
        },
        ]
const adminData = [
    {
        id: 5,
        email: 'admin1@example.com',
        password: '123',
    }
]

export const setData = ()=>{
    localStorage.setItem("employee",JSON.stringify(employeeData))
    localStorage.setItem("admin",JSON.stringify(adminData))
}
setData();

export const getEmployeeData = ()=>{
    return JSON.parse(localStorage.getItem("employee"))
}
export const getAdminData = ()=>{
    return JSON.parse(localStorage.getItem("admin"))
}